export const courses = [
  {
    slug: 'data-analysis',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    icon: 'DA',
    color: '#14B8A6',
    bg: 'rgba(20,184,166,0.1)',
    title: 'Data Analysis',
    subtitle: 'Python | SQL | Power BI | Gen AI',
    duration: '3 Months',
    fee: '₹35,000',
    discount: '₹5,000',
    finalFee: '₹30,000',
    mode: 'Online + Offline (Hybrid)',
    nextBatch: 'Starting Soon',
    description: 'Master the art of data analysis using industry-standard tools combined with the power of Generative AI. Learn to collect, clean, analyze and visualize data to drive real business decisions. This course covers Python, SQL, Power BI, AI tools and predictive analytics — making you a complete data professional.',
    whatYouLearn: [
      'Analyze large datasets using Python, Pandas & NumPy',
      'Write complex SQL queries including joins & window functions',
      'Build stunning interactive dashboards in Power BI with DAX',
      'Apply statistical methods & predictive analytics techniques',
      'Use Gen AI tools like ChatGPT & Claude for data work',
      'Automate workflows using n8n and no-code platforms',
      'Perform EDA & feature engineering on real datasets',
      'Build ML models using KNN, Decision Trees & Random Forests',
    ],
    modules: [
      { name: 'Python Programming for Data Analysis', topics: ['Python basics — data types, control structures & functions', 'Data manipulation with Pandas & NumPy', 'Working with files & data formats (CSV, JSON, Excel)', 'Vibe coding — writing Python with AI assistance', 'Automating repetitive data tasks with Python scripts'] },
      { name: 'Statistics for Data Science', topics: ['Descriptive statistics — mean, median, mode, variance', 'Probability & distributions', 'Hypothesis testing & p-values', 'Inferential statistics & confidence intervals', 'Correlation & regression analysis'] },
      { name: 'Feature Engineering & Data Preprocessing', topics: ['Handling missing data & outliers', 'Encoding categorical variables', 'Feature scaling & normalization', 'Feature selection techniques', 'Transforming raw data into analysis-ready datasets'] },
      { name: 'Exploratory Data Analysis (EDA)', topics: ['Understanding data structure & distributions', 'Identifying trends, patterns & outliers', 'Data visualization with Matplotlib & Seaborn', 'AI-assisted EDA using ChatGPT & Claude', 'Ensuring data quality before modeling'] },
      { name: 'SQL for Data Analysts', topics: ['SQL basics — SELECT, WHERE, GROUP BY, ORDER BY', 'Advanced joins — INNER, LEFT, RIGHT, FULL', 'Window functions & CTEs', 'Subqueries & complex aggregations', 'Working with large datasets in SQL Server'] },
      { name: 'Generative AI Integration', topics: ['Using ChatGPT, Claude, Perplexity & Grok for data work', 'Prompt engineering for data analysis tasks', 'AI-assisted data cleaning & transformation', 'Automating workflows with AI tools', 'No-code automation using n8n platform'] },
      { name: 'Power BI for Visualization & Reporting', topics: ['Power BI Desktop — interface & data connections', 'Data transformation with Power Query', 'DAX formulas & calculated measures', 'Building interactive dashboards & reports', 'AI-driven insights in Power BI', 'Publishing & sharing reports'] },
      { name: 'Predictive Analytics & Machine Learning Basics', topics: ['Introduction to machine learning concepts', 'K-Nearest Neighbors (KNN) algorithm', 'Decision Trees & Random Forests', 'Model evaluation & accuracy metrics', 'Applying predictive models to real datasets'] },
      { name: 'Real-World Capstone Projects', topics: ['End-to-end data analysis on real industry datasets', 'Data cleaning, EDA & feature engineering pipeline', 'Building Power BI dashboards from scratch', 'AI-assisted analysis & automation integration', 'Portfolio project presentation to industry panel'] },
    ],
    tools: ['Python', 'Pandas', 'NumPy', 'SQL', 'Power BI', 'DAX', 'Matplotlib', 'Seaborn', 'ChatGPT', 'Claude', 'n8n', 'Jupyter Notebook'],
    whoShouldJoin: ['Fresh graduates in any stream', 'Commerce & business professionals', 'Working professionals wanting to upskill', 'Anyone interested in a data career'],
    prerequisites: ['Basic computer knowledge', 'No prior coding experience needed', 'Willingness to learn and practice'],
    careerRoles: ['Data Analyst', 'Business Analyst', 'MIS Analyst', 'Reporting Analyst', 'BI Analyst'],
    salary: '₹3.5 LPA – ₹8 LPA',
    faqs: [
      { q: 'Do I need coding experience?', a: 'No prior coding experience is needed. We start from absolute basics and build up gradually.' },
      { q: 'Is this course online or offline?', a: 'We offer both online and offline (classroom) options. You can choose whichever suits you.' },
      { q: 'Will I get a certificate?', a: 'Yes, you will receive a Nettms completion certificate upon successfully finishing the course.' },
      { q: 'Is placement support provided?', a: 'Yes, we provide full placement support including resume building, mock interviews and job referrals.' },
    ],
   seats: 10,
trainer: {
  name: 'K. Shiva',
  experience: '6+ Years',
  role: 'Data Analytics Professional',
  bio: 'K. Shiva is an actively working Data Analytics professional with 6+ years of real industry experience. He currently works in the field and brings live project knowledge directly into the classroom — teaching Python, SQL, Power BI and AI tools exactly the way companies use them today.',
  initials: 'KS',
  color: '#14B8A6',
},
emi: {
  originalFee: '₹30,000',
  emi3: '₹10,000',
},
seats: 10,
testimonials: [
  {
    name: 'Arjun Mehta',
    role: 'Data Analyst — TCS',
    image: null,
    initials: 'AM',
    review: 'I joined Nettms as a commerce graduate with zero coding knowledge. K. Shiva sir explained Python and SQL so clearly that within 3 months I was confident enough to crack my TCS interview. Best investment I ever made!',
    rating: 5,
  },
  {
    name: 'Sneha Reddy',
    role: 'Business Analyst — Infosys',
    image: null,
    initials: 'SR',
    review: 'The Power BI and SQL training was outstanding. Real projects made all the difference — I had actual work to show in my interviews. Got placed at Infosys within 6 weeks of completing the course.',
    rating: 5,
  },
  {
    name: 'Karthik Nair',
    role: 'MIS Analyst — Capgemini',
    image: null,
    initials: 'KN',
    review: 'What sets Nettms apart is the Gen AI integration in the curriculum. Learning ChatGPT and Claude for data tasks gave me an edge over other candidates. Highly recommend to anyone serious about a data career.',
    rating: 5,
  },
],
competitors: [
  { feature: 'Course Duration', nettms: '3 Months', others: '2-3 Months' },
  { feature: 'Gen AI Integration', nettms: '✅ Yes', others: '❌ No' },
  { feature: 'Live Classes', nettms: '✅ Yes', others: '⚠️ Recorded' },
  { feature: 'Real-Time Trainer', nettms: '✅ Industry Pro', others: '❌ Full-time Teacher' },
  { feature: 'Placement Support', nettms: '✅ Full Support', others: '⚠️ Limited' },
  { feature: 'EMI Available', nettms: '✅ Yes', others: '❌ No' },
  { feature: 'Batch Size', nettms: '✅ Max 15', others: '❌ 30+' },
  { feature: 'Real Projects', nettms: '✅ Yes', others: '⚠️ Case Studies Only' },
],
  },
  {
    slug: 'data-science',
    image: 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80',
    icon: 'DS',
    color: '#5AB240',
    bg: 'rgba(90,178,64,0.1)',
    title: 'Data Science',
    subtitle: 'Python | ML | Deep Learning | AI',
    duration: '4 Months',
    fee: '₹35,000',
    discount: '₹5,000',
    finalFee: '₹30,000',
    mode: 'Online + Offline (Hybrid)',
    nextBatch: 'Starting Soon',
    description: 'Become a Data Scientist with hands-on training in Machine Learning, Deep Learning and AI. Learn to build predictive models, work with large datasets and deploy ML solutions in production environments.',
    whatYouLearn: [
      'Build and deploy machine learning models from scratch',
      'Work with neural networks and deep learning frameworks',
      'Develop strong mathematical foundations for ML algorithms',
      'Use industry tools like TensorFlow, PyTorch & Scikit-learn',
      'Apply ML to real-world domains like healthcare & finance',
      'Optimize models with hyperparameter tuning & evaluation',
      'Understand transformer models & advanced deep learning',
      'Deploy ML models on cloud platforms',
    ],
    modules: [
      { name: 'Foundational Concepts', topics: ['Basics of ML and NLP algorithms', 'Core machine learning principles', 'Supervised & unsupervised learning', 'Introduction to natural language processing', 'Model types and use cases'] },
      { name: 'Mathematical Foundations', topics: ['Linear algebra for ML', 'Calculus & gradient descent', 'Probability theory & distributions', 'Statistics for data science', 'Math behind ML algorithms'] },
      { name: 'Industry-Standard Tools', topics: ['Python for data science', 'NumPy & Pandas', 'Scikit-learn for ML', 'TensorFlow & PyTorch', 'Jupyter & Google Colab'] },
      { name: 'Advanced Topics', topics: ['Deep learning & neural networks', 'CNN, RNN & LSTM', 'Reinforcement learning basics', 'Transformer models & attention', 'Transfer learning'] },
      { name: 'Practical Applications', topics: ['ML in healthcare domain', 'ML in finance & e-commerce', 'Real-world case studies', 'End-to-end project development', 'Model deployment with Flask'] },
      { name: 'Optimization Techniques', topics: ['Hyperparameter tuning', 'Model selection strategies', 'Cross-validation techniques', 'Model evaluation metrics', 'Performance optimization'] },
      { name: 'Capstone Project', topics: ['End-to-end ML project', 'Data collection & preprocessing', 'Model building & evaluation', 'Deployment on cloud', 'Portfolio presentation'] },
    ],
    tools: ['Python', 'Scikit-learn', 'TensorFlow', 'PyTorch', 'Pandas', 'NumPy', 'Jupyter', 'AWS SageMaker', 'Flask'],
    whoShouldJoin: ['CS / IT / ECE graduates', 'Data analysts wanting to advance', 'Professionals interested in AI/ML', 'Research enthusiasts'],
    prerequisites: ['Basic Python knowledge helpful but not required', 'Basic mathematics understanding', 'Strong willingness to learn'],
    careerRoles: ['Data Scientist', 'ML Engineer', 'AI Engineer', 'Research Analyst', 'Deep Learning Engineer'],
    salary: '₹5 LPA – ₹15 LPA',
    faqs: [
      { q: 'Is this course suitable for beginners?', a: 'Yes, we start from Python basics. However basic math understanding will be helpful.' },
      { q: 'How many projects will I build?', a: 'You will build multiple mini-projects throughout the course plus one major capstone project.' },
      { q: 'Will I learn AI tools like ChatGPT?', a: 'Yes, we cover NLP and large language model fundamentals as part of the curriculum.' },
      { q: 'What is the placement rate?', a: 'Our overall placement rate is 85%. We actively connect students with our hiring partners.' },
    ],
    seats: 10,
trainer: {
  name: 'K. Shiva',
  experience: '6+ Years',
  role: 'Data Science Professional',
  bio: 'K. Shiva is an actively working Data Science professional with 6+ years of industry experience. He currently works in the field and brings live machine learning and AI knowledge directly into training — teaching what companies actually use in production today.',
  initials: 'KS',
  color: '#5AB240',
},
emi: {
  originalFee: '₹30,000',
  emi3: '₹10,000',
},
testimonials: [
  {
    name: 'Rohit Sharma',
    role: 'Data Scientist — HCL Technologies',
    image: null,
    initials: 'RS',
    review: 'K. Shiva sir is currently working in the industry and that shows in every class. He teaches real production ML code, not just theory. I built 3 end-to-end projects and got placed at HCL within 2 months.',
    rating: 5,
  },
  {
    name: 'Divya Lakshmi',
    role: 'ML Engineer — Tech Mahindra',
    image: null,
    initials: 'DL',
    review: 'The deep learning and neural network modules were incredibly detailed. I came in with basic Python knowledge and left as a confident ML engineer. The placement team was very supportive throughout.',
    rating: 5,
  },
  {
    name: 'Sameer Khan',
    role: 'AI Engineer — Wipro',
    image: null,
    initials: 'SK',
    review: 'From Python basics to deploying ML models on AWS — this course covers everything. The capstone project was exactly what companies look for. Got my Wipro offer letter before even completing the course!',
    rating: 5,
  },
],
competitors: [
  { feature: 'Course Duration', nettms: '4 Months', others: '3-4 Months' },
  { feature: 'Real-Time Trainer', nettms: '✅ Industry Pro', others: '❌ Full-time Teacher' },
  { feature: 'Live Classes', nettms: '✅ Yes', others: '⚠️ Recorded' },
  { feature: 'Deep Learning', nettms: '✅ Yes', others: '⚠️ Basic Only' },
  { feature: 'Placement Support', nettms: '✅ Full Support', others: '⚠️ Limited' },
  { feature: 'EMI Available', nettms: '✅ Yes', others: '❌ No' },
  { feature: 'Batch Size', nettms: '✅ Max 15', others: '❌ 30+' },
  { feature: 'Cloud Deployment', nettms: '✅ Yes', others: '❌ No' },
],
  },
  {
    slug: 'gen-ai',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
    icon: 'AI',
    color: '#A855F7',
    bg: 'rgba(168,85,247,0.1)',
    title: 'Gen AI & Agentic AI',
    subtitle: 'LLMs | LangChain | LangGraph | RAG | AI Agents',
    duration: '3 Months',
    fee: '₹35,000',
    discount: '₹5,000',
    finalFee: '₹30,000',
    mode: 'Online + Offline (Hybrid)',
    nextBatch: 'Starting Soon',
    description: 'Master the cutting edge of Artificial Intelligence. Learn to build Generative AI applications, create autonomous AI agents, build RAG pipelines and deploy production AI systems using LangChain, LangGraph and HuggingFace. This course takes you from AI beginner to advanced agent builder.',
    whatYouLearn: [
      'Understand fundamentals of Generative AI & Large Language Models',
      'Master LangChain & LangGraph for building agent systems',
      'Build autonomous event-driven AI workflows with memory & reasoning',
      'Create RAG pipelines with vector databases',
      'Integrate HuggingFace models into production applications',
      'Deploy AI models to cloud platforms at scale',
      'Build real-world projects — chatbots, RAG agents & auto-research agents',
      'Optimize and monitor deployed AI systems',
    ],
    modules: [
      { name: 'Introduction to Generative AI', topics: ['Fundamentals of Generative AI & its applications', 'Differences between traditional AI & generative models', 'Overview of GPT, Claude, Gemini & open-source LLMs', 'AI ethics, safety & responsible use', 'Tokenization & embeddings explained'] },
      { name: 'Getting Started with LangChain', topics: ['LangChain basics & architecture', 'Setting up development environment', 'Chains, prompts & output parsers', 'Memory & context management', 'Tool integration & callbacks'] },
      { name: 'HuggingFace Integration', topics: ['HuggingFace models & transformers', 'Loading & using pre-trained models', 'Customizing models for specific tasks', 'Fine-tuning HuggingFace models', 'Combining HuggingFace with LangChain'] },
      { name: 'Building Generative AI Applications', topics: ['Building AI-powered chatbots', 'Content generation applications', 'Data augmentation tools', 'Step-by-step real-world projects', 'Integrating multiple AI APIs'] },
      { name: 'RAG Pipelines', topics: ['Retrieval-Augmented Generation concepts', 'Vector databases — Pinecone & ChromaDB', 'Document Q&A systems', 'Combining generative models with retrieval', 'Building production RAG pipelines'] },
      { name: 'Agentic AI with LangGraph', topics: ['Core concepts of Agentic AI', 'LangGraph & LangChain for agent systems', 'Autonomous event-driven AI workflows', 'Memory, reasoning & tool use in agents', 'Single-agent & multi-agent applications'] },
      { name: 'Deployment Strategies', topics: ['Deploying models to cloud platforms', 'On-premise server deployment', 'Scalability & reliability strategies', 'Monitoring deployed AI models', 'Best practices for maintaining AI systems'] },
      { name: 'Optimizing AI Models', topics: ['Model optimization techniques', 'Prompt engineering for production', 'Performance monitoring strategies', 'Updating & retraining AI systems', 'Cost optimization for AI APIs'] },
      { name: 'End-to-End Projects', topics: ['RAG agent from scratch', 'Auto-research AI agent', 'AI chatbot deployment', 'Multi-agent workflow project', 'Portfolio presentation to panel'] },
    ],
    tools: ['Python', 'LangChain', 'LangGraph', 'OpenAI API', 'Anthropic API', 'HuggingFace', 'Pinecone', 'ChromaDB', 'Streamlit'],
    whoShouldJoin: ['Developers wanting to add AI to their skillset', 'Product managers & entrepreneurs', 'Data scientists upskilling to Gen AI', 'Anyone fascinated by AI technology'],
    prerequisites: ['Basic Python knowledge helpful', 'No ML/AI background needed', 'Curiosity and enthusiasm for AI'],
    careerRoles: ['AI Engineer', 'Prompt Engineer', 'LLM Application Developer', 'AI Product Manager', 'Gen AI Consultant'],
    salary: '₹6 LPA – ₹18 LPA',
    faqs: [
      { q: 'Do I need ML experience?', a: 'No prior ML experience needed. We focus on application development with AI, not building models from scratch.' },
      { q: 'Which AI tools will I learn?', a: 'You will work with OpenAI, Anthropic Claude, LangChain, LangGraph, HuggingFace, Pinecone and more.' },
      { q: 'Is Gen AI a stable career?', a: 'Gen AI is the fastest growing field in tech right now with massive demand and very high salaries.' },
      { q: 'Will I build real AI applications?', a: 'Yes, you will build multiple AI applications including a chatbot, RAG system and autonomous AI agent.' },
    ],
    seats: 10,
trainer: {
  name: 'Ravi',
  experience: '5+ Years',
  role: 'AI & Gen AI Professional',
  bio: 'Ravi is an actively working AI professional with 5+ years of industry experience. He currently builds Generative AI applications and autonomous agent systems in the real world — bringing LangChain, LangGraph, RAG pipelines and production AI deployment knowledge directly into training.',
  initials: 'RV',
  color: '#A855F7',
},
emi: {
  originalFee: '₹30,000',
  emi3: '₹10,000',
},
testimonials: [
  {
    name: 'Nikhil Reddy',
    role: 'AI Engineer — Deloitte',
    image: null,
    initials: 'NR',
    review: 'Ravi sir is actively building AI agents in the real world and brings that knowledge directly to class. The LangChain and RAG pipeline projects were mind blowing. Got placed at Deloitte with the highest package in my batch!',
    rating: 5,
  },
  {
    name: 'Preethi Iyer',
    role: 'Prompt Engineer — KPMG',
    image: null,
    initials: 'PI',
    review: 'This is the most future-ready course I have ever done. Building autonomous AI agents from scratch was something I never imagined I could do. Nettms made it simple and practical. KPMG hired me within 3 weeks!',
    rating: 5,
  },
  {
    name: 'Suresh Babu',
    role: 'LLM Developer — Tech Mahindra',
    image: null,
    initials: 'SB',
    review: 'The hands-on experience with OpenAI, LangGraph and vector databases is unmatched. This course is perfect for anyone who wants to build a career in AI. The placement support was excellent too.',
    rating: 5,
  },
],
competitors: [
  { feature: 'Course Duration', nettms: '3 Months', others: '2-3 Months' },
  { feature: 'Real-Time Trainer', nettms: '✅ Industry Pro', others: '❌ Full-time Teacher' },
  { feature: 'LangChain + LangGraph', nettms: '✅ Both', others: '⚠️ Basic Only' },
  { feature: 'RAG Pipelines', nettms: '✅ Yes', others: '❌ No' },
  { feature: 'AI Agents', nettms: '✅ Yes', others: '❌ No' },
  { feature: 'Placement Support', nettms: '✅ Full Support', others: '⚠️ Limited' },
  { feature: 'EMI Available', nettms: '✅ Yes', others: '❌ No' },
  { feature: 'Batch Size', nettms: '✅ Max 15', others: '❌ 30+' },
],
  },
  {
    slug: 'bim',
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
    icon: 'BIM',
    color: '#F59E0B',
    bg: 'rgba(245,158,11,0.1)',
    title: 'BIM',
    subtitle: 'Revit | AutoCAD | Navisworks | 3D Modeling',
    duration: '3 Months',
    fee: '₹30,000',
    discount: '₹5,000',
    finalFee: '₹25,000',
    mode: 'Online + Offline (Hybrid)',
    nextBatch: 'Starting Soon',
    description: 'Building Information Modeling (BIM) is transforming the construction and engineering industry. Learn to design, model and manage building projects using industry-leading tools like Revit, AutoCAD and Navisworks. Perfect for Civil, Mechanical and ECE engineers.',
    whatYouLearn: [
      'Create 3D building models using Autodesk Revit',
      'Produce construction drawings with AutoCAD',
      'Perform clash detection using Navisworks',
      'Manage BIM project workflows and standards',
      'Collaborate on multi-discipline BIM projects',
      'Export and work with IFC and other BIM formats',
    ],
    modules: [
      { name: 'AutoCAD Fundamentals', topics: ['2D drafting & annotation', 'Layers & blocks', 'Plotting & printing', 'AutoCAD shortcuts'] },
      { name: 'Revit Architecture', topics: ['Revit interface & basics', 'Walls, floors & roofs', 'Doors, windows & stairs', 'Schedules & sheets'] },
      { name: 'Revit Structure & MEP', topics: ['Structural elements', 'MEP systems modeling', 'Coordination views', 'Family creation'] },
      { name: 'BIM Coordination', topics: ['Clash detection', 'Navisworks basics', 'IFC file format', 'BIM 360 collaboration'] },
      { name: 'BIM Standards & Workflow', topics: ['LOD standards', 'BIM execution plans', 'Project collaboration', 'Industry workflows'] },
      { name: 'Capstone Project', topics: ['Complete building model', 'Multi-discipline coordination', 'Construction documents', 'Client presentation'] },
    ],
    tools: ['Autodesk Revit', 'AutoCAD', 'Navisworks', 'BIM 360', 'Dynamo', 'Lumion', 'IFC Viewer'],
    whoShouldJoin: ['Civil engineering graduates', 'Mechanical engineers', 'Architecture graduates', 'ECE professionals moving to infrastructure'],
    prerequisites: ['Engineering background (Civil/Mech/ECE preferred)', 'Basic computer knowledge', 'No prior CAD experience needed'],
    careerRoles: ['BIM Modeler', 'BIM Coordinator', 'Revit Technician', 'CAD Designer', 'BIM Manager'],
    salary: '₹3 LPA – ₹8 LPA',
    faqs: [
      { q: 'Is BIM only for Civil engineers?', a: 'No, BIM is used by Civil, Mechanical, Electrical and Architecture professionals. All are welcome.' },
      { q: 'Is there software provided?', a: 'Yes, we provide access to all required software during the course. Student licenses are available.' },
      { q: 'What is the scope of BIM in India?', a: 'BIM adoption is growing rapidly in India with government mandating BIM for all public projects above a certain value.' },
      { q: 'Can I work abroad with BIM skills?', a: 'Yes, BIM is widely used in the Middle East, UK, Australia and USA. It opens international opportunities.' },
    ],
    seats: 10,
trainer: {
  name: 'Vijayababu',
  experience: '15+ Years',
  role: 'BIM & CAD Professional',
  bio: 'Vijayababu is an actively working BIM and CAD professional with 15+ years of real industry experience. He currently works on large-scale infrastructure and construction projects — bringing live Revit, AutoCAD and Navisworks workflows directly into training sessions.',
  initials: 'VB',
  color: '#F59E0B',
},
emi: {
  originalFee: '₹25,000',
  emi3: '₹8,500',
},
testimonials: [
  {
    name: 'Ravi Shankar',
    role: 'BIM Modeler — L&T Construction',
    image: null,
    initials: 'RS',
    review: 'Vijayababu sir has 15 years of real construction project experience. Every class felt like being on an actual project site. I mastered Revit and Navisworks and got placed at L&T within a month of completing the course.',
    rating: 5,
  },
  {
    name: 'Kavitha Narayan',
    role: 'Revit Technician — Shapoorji Pallonji',
    image: null,
    initials: 'KN',
    review: 'As a civil engineer I always wanted to learn BIM. Nettms gave me the perfect structured training. The clash detection and BIM coordination modules were excellent. Now working on real infrastructure projects!',
    rating: 5,
  },
  {
    name: 'Mohammed Arif',
    role: 'BIM Coordinator — Larsen & Toubro',
    image: null,
    initials: 'MA',
    review: 'Best BIM training institute in Hyderabad. The combination of AutoCAD and Revit training is unbeatable. Vijayababu sir explains even complex workflows very clearly. Got a job offer before completing the course!',
    rating: 5,
  },
],
competitors: [
  { feature: 'Course Duration', nettms: '3 Months', others: '2-3 Months' },
  { feature: 'Real-Time Trainer', nettms: '✅ 15yr Pro', others: '❌ Full-time Teacher' },
  { feature: 'Revit + AutoCAD', nettms: '✅ Both', others: '⚠️ One Only' },
  { feature: 'Navisworks', nettms: '✅ Yes', others: '❌ No' },
  { feature: 'Live Classes', nettms: '✅ Yes', others: '⚠️ Recorded' },
  { feature: 'Placement Support', nettms: '✅ Full Support', others: '⚠️ Limited' },
  { feature: 'EMI Available', nettms: '✅ Yes', others: '❌ No' },
  { feature: 'Batch Size', nettms: '✅ Max 15', others: '❌ 30+' },
],
competitors: [
  { feature: 'Course Duration', nettms: '3 Months', others: '2-3 Months' },
  { feature: 'Revit + AutoCAD', nettms: '✅ Both', others: '⚠️ One Only' },
  { feature: 'Live Classes', nettms: '✅ Yes', others: '⚠️ Recorded' },
  { feature: 'Placement Support', nettms: '✅ Full Support', others: '⚠️ Limited' },
  { feature: 'Navisworks Training', nettms: '✅ Yes', others: '❌ No' },
  { feature: 'EMI Available', nettms: '✅ Yes', others: '❌ No' },
  { feature: 'Certification', nettms: '✅ Nettms Cert', others: '✅ Yes' },
  { feature: 'Batch Size', nettms: '✅ Max 15', others: '❌ 30+' },
],
  },
]

export function getCourse(slug) {
  return courses.find(c => c.slug === slug)
}
