export const courses = [
  {
    slug: 'data-analysis',
    icon: 'DA',
    color: '#14B8A6',
    bg: 'rgba(20,184,166,0.1)',
    title: 'Data Analysis',
    subtitle: 'Python | SQL | Power BI | Gen AI',
    duration: '3 Months',
    fee: '₹35,000',
    discount: '₹5,000',
    finalFee: '₹30,000',
    mode: 'Online + Offline (Hybrid)',
    nextBatch: 'Starting Soon',
    description: 'Master the art of data analysis using industry-standard tools combined with the power of Generative AI. Learn to collect, clean, analyze and visualize data to drive real business decisions. This course covers Python, SQL, Power BI, AI tools and predictive analytics — making you a complete data professional.',
    whatYouLearn: [
      'Analyze large datasets using Python, Pandas & NumPy',
      'Write complex SQL queries including joins & window functions',
      'Build stunning interactive dashboards in Power BI with DAX',
      'Apply statistical methods & predictive analytics techniques',
      'Use Gen AI tools like ChatGPT & Claude for data work',
      'Automate workflows using n8n and no-code platforms',
      'Perform EDA & feature engineering on real datasets',
      'Build ML models using KNN, Decision Trees & Random Forests',
    ],
    modules: [
      { name: 'Python Programming for Data Analysis', topics: ['Python basics — data types, control structures & functions', 'Data manipulation with Pandas & NumPy', 'Working with files & data formats (CSV, JSON, Excel)', 'Vibe coding — writing Python with AI assistance', 'Automating repetitive data tasks with Python scripts'] },
      { name: 'Statistics for Data Science', topics: ['Descriptive statistics — mean, median, mode, variance', 'Probability & distributions', 'Hypothesis testing & p-values', 'Inferential statistics & confidence intervals', 'Correlation & regression analysis'] },
      { name: 'Feature Engineering & Data Preprocessing', topics: ['Handling missing data & outliers', 'Encoding categorical variables', 'Feature scaling & normalization', 'Feature selection techniques', 'Transforming raw data into analysis-ready datasets'] },
      { name: 'Exploratory Data Analysis (EDA)', topics: ['Understanding data structure & distributions', 'Identifying trends, patterns & outliers', 'Data visualization with Matplotlib & Seaborn', 'AI-assisted EDA using ChatGPT & Claude', 'Ensuring data quality before modeling'] },
      { name: 'SQL for Data Analysts', topics: ['SQL basics — SELECT, WHERE, GROUP BY, ORDER BY', 'Advanced joins — INNER, LEFT, RIGHT, FULL', 'Window functions & CTEs', 'Subqueries & complex aggregations', 'Working with large datasets in SQL Server'] },
      { name: 'Generative AI Integration', topics: ['Using ChatGPT, Claude, Perplexity & Grok for data work', 'Prompt engineering for data analysis tasks', 'AI-assisted data cleaning & transformation', 'Automating workflows with AI tools', 'No-code automation using n8n platform'] },
      { name: 'Power BI for Visualization & Reporting', topics: ['Power BI Desktop — interface & data connections', 'Data transformation with Power Query', 'DAX formulas & calculated measures', 'Building interactive dashboards & reports', 'AI-driven insights in Power BI', 'Publishing & sharing reports'] },
      { name: 'Predictive Analytics & Machine Learning Basics', topics: ['Introduction to machine learning concepts', 'K-Nearest Neighbors (KNN) algorithm', 'Decision Trees & Random Forests', 'Model evaluation & accuracy metrics', 'Applying predictive models to real datasets'] },
      { name: 'Real-World Capstone Projects', topics: ['End-to-end data analysis on real industry datasets', 'Data cleaning, EDA & feature engineering pipeline', 'Building Power BI dashboards from scratch', 'AI-assisted analysis & automation integration', 'Portfolio project presentation to industry panel'] },
    ],
    tools: ['Python', 'Pandas', 'NumPy', 'SQL', 'Power BI', 'DAX', 'Matplotlib', 'Seaborn', 'ChatGPT', 'Claude', 'n8n', 'Jupyter Notebook'],
    whoShouldJoin: ['Fresh graduates in any stream', 'Commerce & business professionals', 'Working professionals wanting to upskill', 'Anyone interested in a data career'],
    prerequisites: ['Basic computer knowledge', 'No prior coding experience needed', 'Willingness to learn and practice'],
    careerRoles: ['Data Analyst', 'Business Analyst', 'MIS Analyst', 'Reporting Analyst', 'BI Analyst'],
    salary: '₹3.5 LPA – ₹8 LPA',
    faqs: [
      { q: 'Do I need coding experience?', a: 'No prior coding experience is needed. We start from absolute basics and build up gradually.' },
      { q: 'Is this course online or offline?', a: 'We offer both online and offline (classroom) options. You can choose whichever suits you.' },
      { q: 'Will I get a certificate?', a: 'Yes, you will receive a Nettms completion certificate upon successfully finishing the course.' },
      { q: 'Is placement support provided?', a: 'Yes, we provide full placement support including resume building, mock interviews and job referrals.' },
    ],
  },
  {
    slug: 'data-science',
    icon: 'DS',
    color: '#5AB240',
    bg: 'rgba(90,178,64,0.1)',
    title: 'Data Science',
    subtitle: 'Python | ML | Deep Learning | AI',
    duration: '4 Months',
    fee: '₹35,000',
    discount: '₹5,000',
    finalFee: '₹30,000',
    mode: 'Online + Offline (Hybrid)',
    nextBatch: 'Starting Soon',
    description: 'Become a Data Scientist with hands-on training in Machine Learning, Deep Learning and AI. Learn to build predictive models, work with large datasets and deploy ML solutions in production environments.',
    whatYouLearn: [
      'Build and deploy machine learning models from scratch',
      'Work with neural networks and deep learning frameworks',
      'Develop strong mathematical foundations for ML algorithms',
      'Use industry tools like TensorFlow, PyTorch & Scikit-learn',
      'Apply ML to real-world domains like healthcare & finance',
      'Optimize models with hyperparameter tuning & evaluation',
      'Understand transformer models & advanced deep learning',
      'Deploy ML models on cloud platforms',
    ],
    modules: [
      { name: 'Foundational Concepts', topics: ['Basics of ML and NLP algorithms', 'Core machine learning principles', 'Supervised & unsupervised learning', 'Introduction to natural language processing', 'Model types and use cases'] },
      { name: 'Mathematical Foundations', topics: ['Linear algebra for ML', 'Calculus & gradient descent', 'Probability theory & distributions', 'Statistics for data science', 'Math behind ML algorithms'] },
      { name: 'Industry-Standard Tools', topics: ['Python for data science', 'NumPy & Pandas', 'Scikit-learn for ML', 'TensorFlow & PyTorch', 'Jupyter & Google Colab'] },
      { name: 'Advanced Topics', topics: ['Deep learning & neural networks', 'CNN, RNN & LSTM', 'Reinforcement learning basics', 'Transformer models & attention', 'Transfer learning'] },
      { name: 'Practical Applications', topics: ['ML in healthcare domain', 'ML in finance & e-commerce', 'Real-world case studies', 'End-to-end project development', 'Model deployment with Flask'] },
      { name: 'Optimization Techniques', topics: ['Hyperparameter tuning', 'Model selection strategies', 'Cross-validation techniques', 'Model evaluation metrics', 'Performance optimization'] },
      { name: 'Capstone Project', topics: ['End-to-end ML project', 'Data collection & preprocessing', 'Model building & evaluation', 'Deployment on cloud', 'Portfolio presentation'] },
    ],
    tools: ['Python', 'Scikit-learn', 'TensorFlow', 'PyTorch', 'Pandas', 'NumPy', 'Jupyter', 'AWS SageMaker', 'Flask'],
    whoShouldJoin: ['CS / IT / ECE graduates', 'Data analysts wanting to advance', 'Professionals interested in AI/ML', 'Research enthusiasts'],
    prerequisites: ['Basic Python knowledge helpful but not required', 'Basic mathematics understanding', 'Strong willingness to learn'],
    careerRoles: ['Data Scientist', 'ML Engineer', 'AI Engineer', 'Research Analyst', 'Deep Learning Engineer'],
    salary: '₹5 LPA – ₹15 LPA',
    faqs: [
      { q: 'Is this course suitable for beginners?', a: 'Yes, we start from Python basics. However basic math understanding will be helpful.' },
      { q: 'How many projects will I build?', a: 'You will build multiple mini-projects throughout the course plus one major capstone project.' },
      { q: 'Will I learn AI tools like ChatGPT?', a: 'Yes, we cover NLP and large language model fundamentals as part of the curriculum.' },
      { q: 'What is the placement rate?', a: 'Our overall placement rate is 85%. We actively connect students with our hiring partners.' },
    ],
  },
  {
    slug: 'devops',
    icon: 'AWS',
    color: '#F97316',
    bg: 'rgba(249,115,22,0.1)',
    title: 'Multi-Cloud DevOps',
    subtitle: 'AWS | Azure | Docker | Kubernetes',
    duration: '3-4 Months',
    fee: '₹35,000',
    discount: '₹5,000',
    finalFee: '₹30,000',
    mode: 'Online + Offline (Hybrid)',
    nextBatch: 'Starting Soon',
    description: 'Master DevOps practices and multi-cloud infrastructure on both AWS and Microsoft Azure. Learn to build CI/CD pipelines, containerize applications and manage cloud infrastructure at scale using industry-standard tools.',
    whatYouLearn: [
      'Design and manage cloud infrastructure on AWS and Azure',
      'Build end-to-end CI/CD pipelines',
      'Containerize applications with Docker and orchestrate with Kubernetes',
      'Write Infrastructure as Code using Terraform and Ansible',
      'Implement monitoring with Prometheus, Grafana and ELK Stack',
      'Apply DevSecOps practices for secure deployments',
    ],
    modules: [
      { name: 'Linux & Shell Scripting', topics: ['Linux fundamentals', 'Shell scripting', 'Networking basics', 'File systems & permissions'] },
      { name: 'Git & Version Control', topics: ['Git fundamentals', 'Branching strategies', 'GitHub Actions', 'Pull requests & reviews'] },
      { name: 'Docker & Containers', topics: ['Docker architecture', 'Dockerfile creation', 'Docker Compose', 'Container registries'] },
      { name: 'Kubernetes', topics: ['K8s architecture', 'Deployments & services', 'Helm charts', 'Auto-scaling'] },
      { name: 'AWS Cloud', topics: ['IAM, VPC, EC2, S3', 'RDS & Lambda', 'EKS & ECS', 'CloudWatch & CodePipeline'] },
      { name: 'Azure Cloud', topics: ['Azure fundamentals', 'AKS & App Services', 'Azure DevOps pipelines', 'Azure Monitor'] },
      { name: 'IaC & CI/CD', topics: ['Terraform basics', 'Ansible automation', 'Jenkins pipelines', 'GitHub Actions workflows'] },
      { name: 'Monitoring & Security', topics: ['Prometheus & Grafana', 'ELK Stack', 'DevSecOps principles', 'Cloud security basics'] },
    ],
    tools: ['AWS', 'Azure', 'Docker', 'Kubernetes', 'Terraform', 'Ansible', 'Jenkins', 'Prometheus', 'Grafana'],
    whoShouldJoin: ['CS/IT graduates looking for cloud careers', 'Software developers moving to DevOps', 'System administrators upskilling', 'IT professionals targeting cloud certifications'],
    prerequisites: ['Basic programming knowledge', 'Familiarity with computers and internet', 'No prior cloud experience needed'],
    careerRoles: ['DevOps Engineer', 'Cloud Engineer', 'Site Reliability Engineer', 'Platform Engineer', 'CI/CD Engineer'],
    salary: '₹4.5 LPA – ₹12 LPA',
    faqs: [
      { q: 'Do I need cloud experience?', a: 'No prior cloud experience needed. We start from Linux basics and build up to advanced cloud topics.' },
      { q: 'Will this help with AWS/Azure certifications?', a: 'Yes, the curriculum is aligned with AWS Solutions Architect and Azure Administrator (AZ-104) certifications.' },
      { q: 'Is this course hands-on?', a: 'Absolutely. You will work on live cloud environments and build real CI/CD pipelines throughout the course.' },
      { q: 'What is the job market like for DevOps?', a: 'DevOps is one of the highest paying IT roles in India with massive demand across all company sizes.' },
    ],
  },
  {
    slug: 'python-fullstack',
    icon: 'PY',
    color: '#3B82F6',
    bg: 'rgba(59,130,246,0.1)',
    title: 'Full Stack Python',
    subtitle: 'Django | React.js | REST APIs | Cloud',
    duration: '4-5 Months',
    fee: '₹35,000',
    discount: '₹5,000',
    finalFee: '₹30,000',
    mode: 'Online + Offline (Hybrid)',
    nextBatch: 'Starting Soon',
    description: 'Become a complete Full Stack Python Developer. Master backend development with Django and Django REST Framework, build dynamic frontends with React.js and deploy production applications on cloud platforms.',
    whatYouLearn: [
      'Build production-ready backend APIs with Django & DRF',
      'Create dynamic frontends with React.js and Tailwind CSS',
      'Design and implement relational databases with PostgreSQL',
      'Implement JWT authentication and secure REST APIs',
      'Deploy applications to AWS and Heroku',
      'Use Git for version control and collaborative development',
    ],
    modules: [
      { name: 'Python Fundamentals', topics: ['Python basics & OOP', 'Data structures', 'File handling', 'Exception handling'] },
      { name: 'Database & SQL', topics: ['MySQL/PostgreSQL', 'CRUD operations', 'ORM concepts', 'Database design'] },
      { name: 'Django Backend', topics: ['MVT architecture', 'URL routing & views', 'Django ORM & models', 'Authentication & admin'] },
      { name: 'Django REST Framework', topics: ['REST API concepts', 'Serializers & ViewSets', 'JWT authentication', 'API testing with Postman'] },
      { name: 'Frontend Fundamentals', topics: ['HTML5 & CSS3', 'JavaScript ES6+', 'Responsive design', 'DOM manipulation'] },
      { name: 'React.js', topics: ['Components & JSX', 'Hooks & state management', 'React Router', 'Axios & API integration'] },
      { name: 'Deployment & DevOps', topics: ['Git & GitHub', 'AWS EC2 deployment', 'NGINX & Gunicorn', 'Environment variables'] },
      { name: 'Capstone Project', topics: ['Full stack web application', 'Frontend + backend integration', 'Database design', 'Cloud deployment'] },
    ],
    tools: ['Python', 'Django', 'React.js', 'PostgreSQL', 'REST APIs', 'Git', 'AWS', 'Tailwind CSS', 'Postman'],
    whoShouldJoin: ['CS/IT/ECE graduates', 'Non-CS graduates wanting to code', 'Backend developers learning frontend', 'Anyone who wants to build web products'],
    prerequisites: ['Basic computer knowledge', 'No prior coding experience needed', 'Logical thinking mindset'],
    careerRoles: ['Python Developer', 'Full Stack Developer', 'Backend Developer', 'Django Developer', 'Software Engineer'],
    salary: '₹3.5 LPA – ₹10 LPA',
    faqs: [
      { q: 'Do I need to know Python before joining?', a: 'No, we start from absolute Python basics. Complete beginners are welcome.' },
      { q: 'Will I learn both frontend and backend?', a: 'Yes, this is a complete full stack course covering Django backend and React.js frontend.' },
      { q: 'How many projects will I build?', a: 'You will build multiple projects and one major capstone full stack application.' },
      { q: 'Is freelancing possible after this course?', a: 'Absolutely. Python and Django are top choices for freelance web development worldwide.' },
    ],
  },
  {
    slug: 'gen-ai',
    icon: 'AI',
    color: '#A855F7',
    bg: 'rgba(168,85,247,0.1)',
    title: 'Gen AI & Agentic AI',
    subtitle: 'LLMs | LangChain | LangGraph | RAG | AI Agents',
    duration: '3 Months',
    fee: '₹35,000',
    discount: '₹5,000',
    finalFee: '₹30,000',
    mode: 'Online + Offline (Hybrid)',
    nextBatch: 'Starting Soon',
    description: 'Master the cutting edge of Artificial Intelligence. Learn to build Generative AI applications, create autonomous AI agents, build RAG pipelines and deploy production AI systems using LangChain, LangGraph and HuggingFace. This course takes you from AI beginner to advanced agent builder.',
    whatYouLearn: [
      'Understand fundamentals of Generative AI & Large Language Models',
      'Master LangChain & LangGraph for building agent systems',
      'Build autonomous event-driven AI workflows with memory & reasoning',
      'Create RAG pipelines with vector databases',
      'Integrate HuggingFace models into production applications',
      'Deploy AI models to cloud platforms at scale',
      'Build real-world projects — chatbots, RAG agents & auto-research agents',
      'Optimize and monitor deployed AI systems',
    ],
    modules: [
      { name: 'Introduction to Generative AI', topics: ['Fundamentals of Generative AI & its applications', 'Differences between traditional AI & generative models', 'Overview of GPT, Claude, Gemini & open-source LLMs', 'AI ethics, safety & responsible use', 'Tokenization & embeddings explained'] },
      { name: 'Getting Started with LangChain', topics: ['LangChain basics & architecture', 'Setting up development environment', 'Chains, prompts & output parsers', 'Memory & context management', 'Tool integration & callbacks'] },
      { name: 'HuggingFace Integration', topics: ['HuggingFace models & transformers', 'Loading & using pre-trained models', 'Customizing models for specific tasks', 'Fine-tuning HuggingFace models', 'Combining HuggingFace with LangChain'] },
      { name: 'Building Generative AI Applications', topics: ['Building AI-powered chatbots', 'Content generation applications', 'Data augmentation tools', 'Step-by-step real-world projects', 'Integrating multiple AI APIs'] },
      { name: 'RAG Pipelines', topics: ['Retrieval-Augmented Generation concepts', 'Vector databases — Pinecone & ChromaDB', 'Document Q&A systems', 'Combining generative models with retrieval', 'Building production RAG pipelines'] },
      { name: 'Agentic AI with LangGraph', topics: ['Core concepts of Agentic AI', 'LangGraph & LangChain for agent systems', 'Autonomous event-driven AI workflows', 'Memory, reasoning & tool use in agents', 'Single-agent & multi-agent applications'] },
      { name: 'Deployment Strategies', topics: ['Deploying models to cloud platforms', 'On-premise server deployment', 'Scalability & reliability strategies', 'Monitoring deployed AI models', 'Best practices for maintaining AI systems'] },
      { name: 'Optimizing AI Models', topics: ['Model optimization techniques', 'Prompt engineering for production', 'Performance monitoring strategies', 'Updating & retraining AI systems', 'Cost optimization for AI APIs'] },
      { name: 'End-to-End Projects', topics: ['RAG agent from scratch', 'Auto-research AI agent', 'AI chatbot deployment', 'Multi-agent workflow project', 'Portfolio presentation to panel'] },
    ],
    tools: ['Python', 'LangChain', 'LangGraph', 'OpenAI API', 'Anthropic API', 'HuggingFace', 'Pinecone', 'ChromaDB', 'Streamlit'],
    whoShouldJoin: ['Developers wanting to add AI to their skillset', 'Product managers & entrepreneurs', 'Data scientists upskilling to Gen AI', 'Anyone fascinated by AI technology'],
    prerequisites: ['Basic Python knowledge helpful', 'No ML/AI background needed', 'Curiosity and enthusiasm for AI'],
    careerRoles: ['AI Engineer', 'Prompt Engineer', 'LLM Application Developer', 'AI Product Manager', 'Gen AI Consultant'],
    salary: '₹6 LPA – ₹18 LPA',
    faqs: [
      { q: 'Do I need ML experience?', a: 'No prior ML experience needed. We focus on application development with AI, not building models from scratch.' },
      { q: 'Which AI tools will I learn?', a: 'You will work with OpenAI, Anthropic Claude, LangChain, LangGraph, HuggingFace, Pinecone and more.' },
      { q: 'Is Gen AI a stable career?', a: 'Gen AI is the fastest growing field in tech right now with massive demand and very high salaries.' },
      { q: 'Will I build real AI applications?', a: 'Yes, you will build multiple AI applications including a chatbot, RAG system and autonomous AI agent.' },
    ],
  },
  {
    slug: 'bim',
    icon: 'BIM',
    color: '#F59E0B',
    bg: 'rgba(245,158,11,0.1)',
    title: 'BIM',
    subtitle: 'Revit | AutoCAD | Navisworks | 3D Modeling',
    duration: '3 Months',
    fee: '₹30,000',
    discount: '₹5,000',
    finalFee: '₹25,000',
    mode: 'Online + Offline (Hybrid)',
    nextBatch: 'Starting Soon',
    description: 'Building Information Modeling (BIM) is transforming the construction and engineering industry. Learn to design, model and manage building projects using industry-leading tools like Revit, AutoCAD and Navisworks. Perfect for Civil, Mechanical and ECE engineers.',
    whatYouLearn: [
      'Create 3D building models using Autodesk Revit',
      'Produce construction drawings with AutoCAD',
      'Perform clash detection using Navisworks',
      'Manage BIM project workflows and standards',
      'Collaborate on multi-discipline BIM projects',
      'Export and work with IFC and other BIM formats',
    ],
    modules: [
      { name: 'AutoCAD Fundamentals', topics: ['2D drafting & annotation', 'Layers & blocks', 'Plotting & printing', 'AutoCAD shortcuts'] },
      { name: 'Revit Architecture', topics: ['Revit interface & basics', 'Walls, floors & roofs', 'Doors, windows & stairs', 'Schedules & sheets'] },
      { name: 'Revit Structure & MEP', topics: ['Structural elements', 'MEP systems modeling', 'Coordination views', 'Family creation'] },
      { name: 'BIM Coordination', topics: ['Clash detection', 'Navisworks basics', 'IFC file format', 'BIM 360 collaboration'] },
      { name: 'BIM Standards & Workflow', topics: ['LOD standards', 'BIM execution plans', 'Project collaboration', 'Industry workflows'] },
      { name: 'Capstone Project', topics: ['Complete building model', 'Multi-discipline coordination', 'Construction documents', 'Client presentation'] },
    ],
    tools: ['Autodesk Revit', 'AutoCAD', 'Navisworks', 'BIM 360', 'Dynamo', 'Lumion', 'IFC Viewer'],
    whoShouldJoin: ['Civil engineering graduates', 'Mechanical engineers', 'Architecture graduates', 'ECE professionals moving to infrastructure'],
    prerequisites: ['Engineering background (Civil/Mech/ECE preferred)', 'Basic computer knowledge', 'No prior CAD experience needed'],
    careerRoles: ['BIM Modeler', 'BIM Coordinator', 'Revit Technician', 'CAD Designer', 'BIM Manager'],
    salary: '₹3 LPA – ₹8 LPA',
    faqs: [
      { q: 'Is BIM only for Civil engineers?', a: 'No, BIM is used by Civil, Mechanical, Electrical and Architecture professionals. All are welcome.' },
      { q: 'Is there software provided?', a: 'Yes, we provide access to all required software during the course. Student licenses are available.' },
      { q: 'What is the scope of BIM in India?', a: 'BIM adoption is growing rapidly in India with government mandating BIM for all public projects above a certain value.' },
      { q: 'Can I work abroad with BIM skills?', a: 'Yes, BIM is widely used in the Middle East, UK, Australia and USA. It opens international opportunities.' },
    ],
  },
  {
    slug: 'medical-coding',
    icon: 'MC',
    color: '#EC4899',
    bg: 'rgba(236,72,153,0.1)',
    title: 'Medical Coding',
    subtitle: 'ICD-10-CM | CPT | HCPCS | CPC Exam Prep',
    duration: '2-3 Months',
    fee: '₹20,000',
    discount: '₹5,000',
    finalFee: '₹15,000',
    mode: 'Online + Offline (Hybrid)',
    nextBatch: 'Starting Soon',
    description: 'Medical Coding is one of the most stable, in-demand and work-from-home friendly careers. Learn to accurately translate medical diagnoses and procedures into universal codes used for billing and insurance claims. Get prepared for the globally recognized AAPC CPC certification.',
    whatYouLearn: [
      'Master ICD-10-CM, CPT and HCPCS Level II coding systems',
      'Read and interpret clinical medical documentation',
      'Apply coding guidelines for inpatient and outpatient settings',
      'Code for 10+ medical specialties',
      'Understand medical billing and denial management',
      'Prepare for the AAPC CPC certification exam',
    ],
    modules: [
      { name: 'Healthcare & Coding Basics', topics: ['US healthcare system overview', 'Role of medical coders', 'HIPAA compliance', 'Coding guidelines intro'] },
      { name: 'Medical Terminology & Anatomy', topics: ['Body systems overview', 'Medical prefixes & suffixes', 'Disease terminology', 'Clinical documentation'] },
      { name: 'ICD-10-CM Coding', topics: ['ICD-10 structure & conventions', 'Diagnosis coding guidelines', 'Z-codes & E-codes', 'Coding case studies'] },
      { name: 'CPT Procedure Coding', topics: ['CPT code book structure', 'E&M coding', 'Surgery & radiology codes', 'Modifiers usage'] },
      { name: 'HCPCS Level II', topics: ['HCPCS code structure', 'DME coding', 'Drug & supply codes', 'HCPCS modifiers'] },
      { name: 'Specialty Coding', topics: ['Cardiology coding', 'Orthopedics coding', 'Oncology basics', 'Emergency medicine'] },
      { name: 'CPC Exam Preparation', topics: ['AAPC CPC exam structure', 'Mock test practice', 'Time management strategies', 'Exam day tips'] },
    ],
    tools: ['ICD-10-CM Manual', 'CPT Manual', 'Encoder Pro', 'TruCode', 'Epic (overview)', 'AAPC Practice Tests'],
    whoShouldJoin: ['Life science & pharmacy graduates', 'Freshers wanting healthcare IT careers', 'Professionals wanting work-from-home jobs', 'BPO professionals shifting to healthcare'],
    prerequisites: ['Basic English reading and comprehension', '10+2 or graduate in any stream', 'No prior medical background required'],
    careerRoles: ['Medical Coder', 'Clinical Documentation Specialist', 'Coding Auditor', 'Revenue Cycle Analyst'],
    salary: '₹2.5 LPA – ₹6 LPA',
    faqs: [
      { q: 'Do I need a medical background?', a: 'No medical background needed. We teach human anatomy and medical terminology from scratch.' },
      { q: 'Can I work from home after this course?', a: 'Yes, medical coding is one of the best work-from-home careers with many remote opportunities available.' },
      { q: 'What is the CPC certification?', a: 'CPC (Certified Professional Coder) is the globally recognized certification by AAPC. We fully prepare you for this exam.' },
      { q: 'Is there demand for medical coders in India?', a: 'Yes, there is massive demand from hospitals, BPO companies and US healthcare outsourcing firms in India.' },
    ],
  },
]

export function getCourse(slug) {
  return courses.find(c => c.slug === slug)
}