export const masterclasses = {
  'data-analysis': {
    slug: 'data-analysis',
    courseName: 'Data Analysis',
    breadcrumb: 'Data Analysis',
    theme: {
      primary: '#14B8A6',
      primaryRgba: '20,184,166',
      gradientEnd: '#0d9488',
    },
    hero: {
      headline1: 'Data Analysis',
      headline2: 'Masterclass',
      headline3: '— Learn Before You Enroll!',
      tagline: 'In 2 hours, learn <strong>how to do Data Analysis using AI</strong> — from <strong>K. Shiva</strong> (6+ yrs industry). Watch AI build dashboards, write SQL, clean data and generate insights — all from plain English. Skills no boring institute teaches. Just learn!',
      chips: [
        { icon: 'graduation', label: '100% Free' },
        { icon: 'clock', label: '2 Hours Live' },
        { icon: 'user', label: 'K. Shiva — Trainer' },
        { icon: 'pulse', label: 'Limited 15 Seats' },
        { icon: 'mappin', label: 'Online + Offline' },
      ],
      benefits: [
        '100% Free — no hidden charges',
        'Live 2-hour AI-powered session',
        'See AI do your full data analyst job',
        'No coding background required',
        'Certificate of participation',
        'Special discount for attendees who enroll',
      ],
      trainer: {
        initials: 'KS',
        name: 'K. Shiva',
        role: 'Data Analytics Professional — 6+ Years Experience',
        line: 'Currently using AI in industry every day. Teaches the AI-first way of doing data analysis — what companies actually want in 2026.',
      },
    },
    careerSection: {
      badge: 'The AI Shift',
      heading1: 'Why Analysts Who Use AI',
      headingHighlight: 'Earn 2x More',
      heading2: 'in 2026',
      sub: 'Companies are firing slow analysts and hiring AI-fluent ones. An analyst who uses AI does in 1 hour what others do in 1 day. That speed is worth ₹4 LPA more on Day 1. This is the new reality — and the gap is widening fast.',
      stats: [
        { value: '₹4-12 LPA', label: 'Average Salary in India', icon: 'money'},
        { value: '45,000+', label: 'Open Jobs (Naukri 2026)', icon: 'chart'},
        { value: '+35%', label: 'YoY Job Growth', icon: 'trending'},
        { value: 'Top 5', label: 'Career — LinkedIn 2025', icon: 'trophy'},
      ],
    },
    learningsSection: {
      badge: 'What You Take Home',
      heading1: 'In 2 Hours, You Will',
      headingHighlight: 'Know Exactly',
      heading2: '...',
      sub: 'How to do real data analysis using AI — even if you have zero coding background. No fluff. Just live demos from someone doing this in industry every day.',
      learnings: [
        { title: 'AI Does Your Excel Work', desc: 'Upload a messy CSV. Ask AI in plain English. Get cleaned data + insights in seconds. No formulas, no VLOOKUP.' },
        { title: 'AI Builds Power BI Dashboards', desc: 'Tell AI what you want. Watch it build a complete dashboard with KPIs, charts and slicers — live.' },
        { title: 'AI Writes Your SQL Queries', desc: 'Type "show me top 5 customers by revenue last month" in English. AI writes the SQL. You get the answer.' },
        { title: 'AI Generates Python Code', desc: 'No coding background? AI writes Python for you. Data cleaning, analysis, automation — all without typing code.' },
        { title: 'Career Roadmap to ₹6+ LPA', desc: 'Step-by-step path from beginner to AI-Data Analyst role — even from non-tech background.' },
        { title: 'Old vs New Analyst Reality', desc: 'Why 80% of pure Excel/SQL analysts will be replaced by 2027 — and how to be in the 20% that thrive.' },
      ],
    },
    toolsSection: {
      badge: 'AI Tools You Will See',
      heading1: 'Watch',
      headingHighlight: 'AI Do the Whole Job',
      heading2: '— Live!',
      sub: 'No theory. You will watch the exact AI tools real analysts use today — and see them solve actual business problems in minutes, not hours.',
      tools: [
        { name: 'ChatGPT / Claude', color: '#10A37F', desc: 'The brain. Ask questions in English, get SQL queries, Python code and clean insights instantly.', points: ['Plain English to SQL live', 'Python from descriptions', 'Auto data insights'] },
        { name: 'Power BI + Copilot', color: '#F2C811', desc: 'Microsoft\'s AI inside Power BI builds dashboards from a single sentence. Game-changing speed.', points: ['Dashboard from text prompt', 'Auto KPI generation', 'Smart visuals'] },
        { name: 'AI in Excel & Sheets', color: '#0F9D58', desc: 'AI plugins in Excel/Google Sheets do VLOOKUPs, pivots and analysis from plain English.', points: ['Excel formulas auto-written', 'Auto cleaning & insights', '10x faster than manual'] },
      ],
    },
    agenda: [
      { time: '0:00 – 0:15', topic: 'Why AI Killed the Old Analyst Job', desc: 'Real industry shift — what AI now does and what humans still need to do. The new roles in 2026.' },
      { time: '0:15 – 0:45', topic: 'Live Demo — Solve a Business Problem with AI', desc: 'Real messy data. Real business question. Watch AI clean, analyse and present the answer in 20 minutes.' },
      { time: '0:45 – 1:15', topic: 'AI Builds Your Dashboard & SQL', desc: 'See AI build a Power BI dashboard from one sentence. Watch SQL written from English. Live.' },
      { time: '1:15 – 1:40', topic: 'AI-Data Analyst Career Roadmap', desc: 'Salary ranges, hiring companies, the realistic path to ₹6+ LPA — even from non-tech background.' },
      { time: '1:40 – 2:00', topic: 'Live Q&A with Trainer', desc: 'Ask anything — AI tools, career doubts, course details, placement queries.' },
    ],
    whoShouldAttend: [
      'Fresh graduates in any stream',
      'Commerce / BBA / MBA students',
      'Working professionals wanting to upskill',
      'Anyone curious about a data career',
      'Non-tech background — welcome!',
    ],
    testimonials: [
      { name: 'Priya Reddy', role: 'B.Com → Data Analyst @ HCL', initial: 'PR', quote: 'I attended this masterclass last batch. Within 4 months of joining the course, I got placed at HCL with ₹4.5 LPA. Shiva sir teaches like a friend — every doubt clarified.' },
      { name: 'Karthik Reddy', role: 'B.Tech → Junior Data Analyst @ Cognizant', initial: 'KR', quote: 'The masterclass was eye-opening. I had zero idea about data careers. Now I am working at Cognizant. Worth every minute of those 2 hours!' },
      { name: 'Sneha Kumari', role: 'MBA → Business Analyst @ Deloitte', initial: 'SK', quote: 'Attended the free masterclass thinking I will just try it. Loved the teaching style. Joined the course. 5 months later — Deloitte offer in hand.' },
      { name: 'Ravi Chandra', role: 'BBA → Data Analyst @ Wipro', initial: 'RC', quote: 'Honest, practical, no bluff. Shiva sir is currently working in industry, so what he teaches is exactly what companies want today.' },
    ],
    companies: ['Accenture', 'TCS', 'Infosys', 'Deloitte', 'Cognizant', 'Wipro', 'HCL', 'Capgemini', 'Tech Mahindra', 'IBM', 'Genpact', 'EY'],
    bonuses: [
      { title: 'Power BI Quick Start Guide', desc: '40-page PDF covering essential dashboards, DAX & visuals', value: '₹999' },
      { title: 'Data Analyst Resume Template', desc: 'Ready-to-use template tailored for fresher data analyst roles', value: '₹499' },
      { title: 'Complete Career Roadmap PDF', desc: 'Step-by-step plan from beginner to ₹6+ LPA placement', value: '₹799' },
      { title: 'Free 1-on-1 Career Counselling', desc: '30-minute personal session with K. Shiva on Zoom', value: '₹1,500' },
      { title: 'Exclusive Course Discount', desc: 'Up to ₹10,000 off if you enroll within 7 days of masterclass', value: '₹10,000' },
      { title: 'Masterclass Recording', desc: 'Lifetime access to the recording in case you miss anything', value: '₹699' },
    ],
    bonusTotal: '₹14,495',
    faqs: [
      { q: 'Is this masterclass really 100% free? Any hidden charges?', a: 'Yes, completely free. No credit card needed, no hidden fees. Our goal is to give you a real taste of AI-powered data analysis so you can decide if this career is right for you — before you spend on a course.' },
      { q: 'Do I need any prior coding background?', a: 'Not at all. The whole point is that AI does the coding for you. We welcome students from B.Com, BBA, MBA, and any non-tech background. You will see how AI handles SQL, Python and Excel automatically.' },
      { q: 'Will AI replace data analysts? Why should I learn this?', a: 'AI will replace analysts who DON\'T use AI. It will not replace those who DO. Companies still need humans to ask the right questions, verify outputs and make decisions — but they want analysts who use AI to be 10x faster.' },
      { q: 'Which AI tools will you show?', a: 'ChatGPT, Claude, Power BI Copilot, AI in Excel/Sheets — the exact tools used in real companies today. All free or low-cost to use.' },
      { q: 'Will I get a recording if I miss the live session?', a: 'Yes! All registered attendees get the recording within 24 hours. So even if you miss it live, you can watch it whenever convenient.' },
      { q: 'Will the trainer answer my personal career questions?', a: 'Absolutely. The last 20 minutes are dedicated Q&A. You can ask anything — AI tool questions, career doubts, course details, placement queries.' },
      { q: 'Is this masterclass online or offline?', a: 'It is a hybrid live session — you can attend either online (Zoom link) or offline at our Hyderabad campus. Choose what suits you while registering.' },
      { q: 'I am not from Hyderabad — can I still attend?', a: 'Yes! The online session is open for anyone in India. Students attend from Bangalore, Chennai, Vijayawada, Pune, and beyond.' },
    ],
  },

  'data-science': {
    slug: 'data-science',
    courseName: 'Data Science',
    breadcrumb: 'Data Science',
    theme: {
      primary: '#5AB240',
      primaryRgba: '90,178,64',
      gradientEnd: '#3f7d2c',
    },
    hero: {
      headline1: 'Data Science',
      headline2: 'Masterclass',
      headline3: '— Learn Before You Enroll!',
      tagline: 'Attend a FREE 2-hour live masterclass by <strong>K. Shiva</strong> — 6 years industry experience. See real Machine Learning models, Python projects & AI in action. No commitment. Just learn!',
      chips: [
        { icon: 'graduation', label: '100% Free' },
        { icon: 'clock', label: '2 Hours Live' },
        { icon: 'user', label: 'K. Shiva — Trainer' },
        { icon: 'pulse', label: 'Limited 15 Seats' },
        { icon: 'mappin', label: 'Online + Offline' },
      ],
      benefits: [
        '100% Free — no hidden charges',
        'Live 2-hour interactive session',
        'Real demos — Python, ML & Deep Learning',
        'Career roadmap from industry expert',
        'Certificate of participation',
        'Special discount for attendees who enroll',
      ],
      trainer: {
        initials: 'KS',
        name: 'K. Shiva',
        role: 'Data Science Professional — 6+ Years Experience',
        line: 'Currently building ML models in industry. Teaches what companies actually deploy in production.',
      },
    },
    careerSection: {
      badge: 'Career Boom',
      heading1: 'Why Data Science is the',
      headingHighlight: 'Highest Paid',
      heading2: 'Tech Career in 2026',
      sub: 'AI is the future and Data Scientists are the architects of it. Every Indian and global company is racing to hire ML talent — and there is a massive shortage.',
      stats: [
        { value: '₹6-25 LPA', label: 'Average Salary Range', icon: 'money'},
        { value: '60,000+', label: 'Open Jobs in India', icon: 'chart'},
        { value: '+45%', label: 'YoY Demand Growth', icon: 'trending'},
        { value: 'Top 3', label: 'Tech Careers — LinkedIn', icon: 'trophy'},
      ],
    },
    learningsSection: {
      badge: 'What You Take Home',
      heading1: 'In 2 Hours, You Will',
      headingHighlight: 'Know Exactly',
      heading2: '...',
      sub: 'Whether data science is the right career for you. No fluff — just clear, practical insights from someone deploying ML models in production today.',
      learnings: [
        { title: 'Data Scientist Day-to-Day', desc: 'See exactly how data scientists work in companies — from raw data to deployed models.' },
        { title: 'Live Machine Learning Demo', desc: 'Watch a real ML model trained from scratch — predict outcomes, evaluate accuracy live.' },
        { title: 'Python for Data Science', desc: 'See pandas, numpy, scikit-learn used the way industry uses them — fast and clean.' },
        { title: 'Deep Learning Glimpse', desc: 'Get a real preview of neural networks and how they power modern AI products.' },
        { title: 'Career Roadmap', desc: 'Step-by-step path from beginner to ₹8 LPA Data Scientist role — with realistic timelines.' },
        { title: 'Industry Truths', desc: 'What companies actually expect from junior data scientists in 2026 — vs course brochures.' },
      ],
    },
    toolsSection: {
      badge: 'Real Tool Demos',
      heading1: 'See',
      headingHighlight: 'Real ML Tools in Action',
      heading2: '— Not Boring Slides!',
      sub: 'Forget theory. You will watch live demos of the exact tools used by data scientists at top companies today.',
      tools: [
        { name: 'Python', color: '#3776AB', desc: 'The #1 language for data science — pandas, numpy, scikit-learn live.', points: ['Real dataset analysis', 'Pandas in action', 'Build ML model live'] },
        { name: 'Scikit-Learn', color: '#F7931E', desc: 'The go-to ML library used in 90% of industry data science projects.', points: ['Train regression model', 'Classification demo', 'Evaluate accuracy'] },
        { name: 'TensorFlow', color: '#FF6F00', desc: 'Google\'s deep learning framework — powering modern AI products.', points: ['Neural network basics', 'Live demo on real data', 'Deep Learning glimpse'] },
      ],
    },
    agenda: [
      { time: '0:00 – 0:20', topic: 'What is Data Science?', desc: 'Industry overview, scope and how companies use ML to drive decisions and products.' },
      { time: '0:20 – 0:50', topic: 'Live Demo — Build an ML Model', desc: 'Watch a real machine learning model trained from scratch using actual data.' },
      { time: '0:50 – 1:20', topic: 'Python, Pandas & Scikit-Learn', desc: 'See real data wrangling and modelling code — exactly how industry does it!' },
      { time: '1:20 – 1:40', topic: 'Career Roadmap & Salaries', desc: 'Job roles, salary ranges, hiring companies and the realistic path to placement.' },
      { time: '1:40 – 2:00', topic: 'Live Q&A with Trainer', desc: 'Ask anything — career doubts, course details, ML/AI questions, placement queries.' },
    ],
    whoShouldAttend: [
      'B.Tech / BE / B.Sc graduates',
      'CS / IT / ECE students',
      'Maths or statistics graduates',
      'Working professionals targeting AI roles',
      'Anyone curious about ML & AI careers',
    ],
    testimonials: [
      { name: 'Lakshmi Devi', role: 'B.Tech ECE → Data Scientist @ HCL', initial: 'LD', quote: 'I attended Shiva sir\'s free masterclass and that 2 hours changed my career. The way he teaches ML is so simple. Now I work at HCL with ₹6.5 LPA package.' },
      { name: 'Aditya Verma', role: 'B.Sc Maths → ML Engineer @ Mindtree', initial: 'AV', quote: 'The masterclass demo was so practical. I saw a model trained live and it clicked! Joined the course immediately. Got placed within 6 months.' },
      { name: 'Pooja Iyer', role: 'CS Graduate → Data Scientist @ Infosys', initial: 'PI', quote: 'Best decision was attending this free session. The trainer is currently working in industry, not just teaching. That made a huge difference for me.' },
      { name: 'Rohan Patil', role: 'B.Tech → Junior Data Scientist @ Tech M', initial: 'RP', quote: 'Shiva sir doesn\'t just teach — he shows real production code from his daily work. After the masterclass I knew this is what I wanted to do.' },
    ],
    companies: ['TCS', 'Infosys', 'Wipro', 'HCL', 'Accenture', 'Mindtree', 'Tech Mahindra', 'Cognizant', 'Capgemini', 'IBM', 'Mphasis', 'L&T Infotech'],
    bonuses: [
      { title: 'ML Quick Start Guide', desc: '50-page PDF covering essential ML algorithms, Python & projects', value: '₹1,299' },
      { title: 'Data Scientist Resume Template', desc: 'Ready-to-use template tailored for fresher data science roles', value: '₹499' },
      { title: 'Complete Career Roadmap PDF', desc: 'Step-by-step plan from beginner to ₹8+ LPA placement', value: '₹999' },
      { title: 'Free 1-on-1 Career Counselling', desc: '30-minute personal session with K. Shiva on Zoom', value: '₹1,500' },
      { title: 'Exclusive Course Discount', desc: 'Up to ₹10,000 off if you enroll within 7 days of masterclass', value: '₹10,000' },
      { title: 'Masterclass Recording', desc: 'Lifetime access to the recording in case you miss anything', value: '₹699' },
    ],
    bonusTotal: '₹14,996',
    faqs: [
      { q: 'Is this masterclass really 100% free? Any hidden charges?', a: 'Yes, completely free. No credit card needed, no hidden fees. We want you to taste data science before deciding to invest in a course.' },
      { q: 'Do I need to know coding or maths?', a: 'Basic comfort with maths helps but is not mandatory for the masterclass. We explain everything from scratch. Even if you have never coded, you will follow along.' },
      { q: 'Is data science different from data analysis?', a: 'Yes. Data Analysis focuses on insights from existing data using BI tools. Data Science builds predictive models, ML and AI systems — it pays more but is more technical.' },
      { q: 'Will I get a recording if I miss the live session?', a: 'Yes! All registered attendees get the recording within 24 hours. So even if you miss it live, you can watch it whenever convenient.' },
      { q: 'Will the trainer answer my personal questions?', a: 'Absolutely. The last 20 minutes are dedicated Q&A. Career, course, ML topics — ask anything.' },
      { q: 'Is this online or offline?', a: 'It is a hybrid live session — you can attend either online (Zoom) or offline at our Hyderabad campus. Choose while registering.' },
      { q: 'Will I get a certificate?', a: 'Yes, every attendee receives a Certificate of Participation from Nettms Education that can be added to your LinkedIn profile.' },
      { q: 'I am not from Hyderabad — can I still attend?', a: 'Yes! The online session is open to anyone in India. We have students attending from Bangalore, Chennai, Pune, Mumbai and beyond.' },
    ],
  },

  'gen-ai': {
    slug: 'gen-ai',
    courseName: 'Gen AI & Agentic AI',
    breadcrumb: 'Gen AI',
    theme: {
      primary: '#A855F7',
      primaryRgba: '168,85,247',
      gradientEnd: '#7e22ce',
    },
    hero: {
      headline1: 'Gen AI & Agentic AI',
      headline2: 'Masterclass',
      headline3: '— Learn Before You Enroll!',
      tagline: 'Attend a FREE 2-hour live masterclass by <strong>Ravi</strong> — 5 years industry AI experience. See real LangChain agents, RAG pipelines & autonomous AI systems live. No commitment. Just learn!',
      chips: [
        { icon: 'graduation', label: '100% Free' },
        { icon: 'clock', label: '2 Hours Live' },
        { icon: 'user', label: 'Ravi — Trainer' },
        { icon: 'pulse', label: 'Limited 15 Seats' },
        { icon: 'mappin', label: 'Online + Offline' },
      ],
      benefits: [
        '100% Free — no hidden charges',
        'Live 2-hour interactive session',
        'Real demos — LangChain, RAG, Agents',
        'Career roadmap from AI expert',
        'Certificate of participation',
        'Special discount for attendees who enroll',
      ],
      trainer: {
        initials: 'RV',
        name: 'Ravi',
        role: 'AI & Gen AI Professional — 5+ Years Experience',
        line: 'Builds production AI agents & RAG systems daily. Teaches the cutting edge — not yesterday\'s curriculum.',
      },
    },
    careerSection: {
      badge: 'The AI Wave',
      heading1: 'Why Gen AI is the',
      headingHighlight: 'Hottest Career',
      heading2: 'of the Decade',
      sub: 'ChatGPT changed the world in 2 years. Every company is now racing to integrate AI — and there is a global shortage of engineers who can build these systems.',
      stats: [
        { value: '₹8-30 LPA', label: 'Average Salary Range', icon: 'money'},
        { value: '25,000+', label: 'Open AI Jobs in India', icon: 'chart'},
        { value: '+95%', label: 'YoY Demand Growth', icon: 'trending'},
        { value: '#1', label: 'Fastest Growing Skill', icon: 'trophy'},
      ],
    },
    learningsSection: {
      badge: 'What You Take Home',
      heading1: 'In 2 Hours, You Will',
      headingHighlight: 'Know Exactly',
      heading2: '...',
      sub: 'Whether Gen AI is the right career for you. No fluff — just real, hands-on insights from an engineer building production AI agents today.',
      learnings: [
        { title: 'How AI Engineers Work', desc: 'See exactly how AI engineers spend their day — from prompts to production agents.' },
        { title: 'Live LangChain Demo', desc: 'Watch a real AI chatbot built live using LangChain & OpenAI in under 20 minutes.' },
        { title: 'RAG Pipeline in Action', desc: 'See how to make AI answer from your own documents — the most in-demand AI skill today.' },
        { title: 'Build an AI Agent', desc: 'Watch an autonomous agent that searches, decides and acts — built live!' },
        { title: 'Career Roadmap', desc: 'Step-by-step path from beginner to ₹10+ LPA AI Engineer role — even without prior AI background.' },
        { title: 'Industry Reality Check', desc: 'What companies actually want from AI engineers in 2026 — vs the hype.' },
      ],
    },
    toolsSection: {
      badge: 'Real Tool Demos',
      heading1: 'See',
      headingHighlight: 'Real AI Tools in Action',
      heading2: '— Not Theory!',
      sub: 'Forget slides. You will watch live demos of the exact tools used to build modern AI products at top companies.',
      tools: [
        { name: 'LangChain', color: '#1C3C3C', desc: 'The #1 framework for building LLM apps and AI agents in production today.', points: ['Build a real chatbot live', 'Tools & memory demo', 'Agent reasoning explained'] },
        { name: 'LangGraph', color: '#7C3AED', desc: 'The cutting edge of Agentic AI — multi-step autonomous agents.', points: ['Autonomous agent live', 'Multi-tool reasoning', 'Real workflow demo'] },
        { name: 'OpenAI / RAG', color: '#10A37F', desc: 'Combine LLMs with your own data — the most in-demand AI skill in 2026.', points: ['Vector DB live demo', 'Document Q&A built live', 'Production patterns'] },
      ],
    },
    agenda: [
      { time: '0:00 – 0:20', topic: 'What is Gen AI & Agentic AI?', desc: 'Industry overview, scope and how AI is reshaping every industry in 2026.' },
      { time: '0:20 – 0:50', topic: 'Live Demo — Build an AI Chatbot', desc: 'Watch a real chatbot built live using LangChain — connected to OpenAI in minutes.' },
      { time: '0:50 – 1:20', topic: 'RAG & Agentic AI Live', desc: 'See a Retrieval-Augmented Generation system + autonomous agent built live.' },
      { time: '1:20 – 1:40', topic: 'Career Roadmap & Salaries', desc: 'AI roles, salary ranges, hiring companies and the realistic path to placement.' },
      { time: '1:40 – 2:00', topic: 'Live Q&A with Trainer', desc: 'Ask anything — career doubts, course details, LLM topics, placement queries.' },
    ],
    whoShouldAttend: [
      'CS / IT / ECE graduates',
      'Software developers wanting to switch to AI',
      'Python developers upskilling to AI roles',
      'Tech professionals curious about LLMs',
      'Final year students targeting AI jobs',
    ],
    testimonials: [
      { name: 'Vikas Anand', role: 'Software Dev → AI Engineer @ Tech Mahindra', initial: 'VA', quote: 'I attended Ravi sir\'s free masterclass thinking it would be all theory. Instead I saw a real AI agent built live in 2 hours. Joined the course the same day. Now I work in AI.' },
      { name: 'Sruthi Menon', role: 'Python Dev → LLM Engineer @ Mphasis', initial: 'SM', quote: 'The way Ravi sir explains LangChain is unmatched. After the masterclass everything clicked. I am now building agentic AI products at Mphasis.' },
      { name: 'Arjun Krishnan', role: 'B.Tech → Junior AI Engineer @ Wipro', initial: 'AK', quote: 'No course in Hyderabad teaches RAG and Agentic AI like Nettms. The free masterclass alone taught me more than 6 months of YouTube videos.' },
      { name: 'Neha Joshi', role: 'CS Graduate → AI Engineer @ HCL', initial: 'NJ', quote: 'The masterclass was the best 2 hours I spent in my career. Ravi sir is currently working in production AI — that experience shows in every demo.' },
    ],
    companies: ['Microsoft', 'Google', 'Amazon', 'Accenture', 'TCS', 'Infosys', 'HCL', 'Wipro', 'Tech Mahindra', 'Mphasis', 'Cognizant', 'Mindtree'],
    bonuses: [
      { title: 'LangChain Quick Start Guide', desc: '60-page PDF — chains, agents, memory, RAG basics with code', value: '₹1,499' },
      { title: 'AI Engineer Resume Template', desc: 'Ready-to-use template tailored for fresher AI / LLM roles', value: '₹499' },
      { title: 'Complete AI Career Roadmap PDF', desc: 'Step-by-step plan from beginner to ₹10+ LPA AI placement', value: '₹999' },
      { title: 'Free 1-on-1 Career Counselling', desc: '30-minute personal session with Ravi on Zoom', value: '₹1,500' },
      { title: 'Exclusive Course Discount', desc: 'Up to ₹10,000 off if you enroll within 7 days of masterclass', value: '₹10,000' },
      { title: 'Masterclass Recording', desc: 'Lifetime access to the recording in case you miss anything', value: '₹699' },
    ],
    bonusTotal: '₹15,196',
    faqs: [
      { q: 'Is this masterclass really 100% free? Any hidden charges?', a: 'Yes, completely free. No credit card needed, no hidden fees. We want you to see what real Gen AI work looks like before you commit to a course.' },
      { q: 'Do I need a coding or AI background?', a: 'Basic Python knowledge helps. But the masterclass itself is designed so even non-coders can follow the demos and understand the field. The course teaches everything from scratch.' },
      { q: 'How is Gen AI different from regular ML / Data Science?', a: 'Data Science / ML builds models from data. Gen AI uses pre-trained LLMs (like GPT) to build chatbots, agents and AI products — it is more about engineering than maths.' },
      { q: 'Will I get a recording if I miss the live session?', a: 'Yes! All registered attendees get the recording within 24 hours. Watch whenever convenient.' },
      { q: 'Will the trainer answer my personal questions?', a: 'Absolutely. The last 20 minutes are dedicated Q&A. AI questions, career doubts, course queries — ask anything.' },
      { q: 'Is this online or offline?', a: 'It is a hybrid live session — you can attend either online (Zoom) or offline at our Hyderabad campus. Choose while registering.' },
      { q: 'Will I get a certificate?', a: 'Yes, every attendee receives a Certificate of Participation from Nettms Education that can be added to your LinkedIn profile.' },
      { q: 'I am not from Hyderabad — can I still attend?', a: 'Yes! The online session is open to anyone in India. We have students attending from Bangalore, Chennai, Pune, Mumbai and beyond.' },
    ],
  },

  'bim': {
    slug: 'bim',
    courseName: 'BIM',
    breadcrumb: 'BIM',
    theme: {
      primary: '#F59E0B',
      primaryRgba: '245,158,11',
      gradientEnd: '#b45309',
    },
    hero: {
      headline1: 'BIM',
      headline2: 'Master Workshop',
      headline3: '— Your Gateway to Gulf Jobs!',
      tagline: 'A Site Engineer earns ₹12-25k/month in India. A BIM Professional in Gulf earns <strong>₹1.5L+ tax-free</strong>. The difference? One skill set. Attend this FREE 2-hour live workshop by <strong>Vijayababu Nettem</strong> — 11+ years on Abu Dhabi Midfield Terminal, Dubai Mall & NICMAR.',
      chips: [
        { icon: 'graduation', label: '100% Free' },
        { icon: 'clock', label: '2 Hours Live' },
        { icon: 'user', label: 'Vijayababu — Gulf Veteran' },
        { icon: 'pulse', label: 'Limited 15 Seats' },
        { icon: 'mappin', label: 'Online + Offline' },
      ],
      benefits: [
        '100% Free — no hidden charges',
        'Live 2-hour interactive workshop',
        'Real demos — Revit, Navisworks, BOQ',
        'Gulf hiring list (Top 15 companies)',
        'Gulf CV template + interview Qs',
        'Special discount for attendees',
      ],
      trainer: {
        initials: 'VN',
        name: 'Vijayababu Nettem',
        role: 'BIM Professional — 11+ Years Gulf Experience',
        line: 'Abu Dhabi Midfield Terminal · Dubai Mall · NICMAR. Teaches what Gulf clients actually demand on day one.',
      },
    },
    careerSection: {
      badge: 'Gulf Opportunity',
      heading1: 'Why BIM is the',
      headingHighlight: '#1 Gulf Career',
      heading2: 'for Indian Engineers',
      sub: 'BIM is now mandatory on every project above ₹100 crore for L&T, Shapoorji, Tata Projects and ALL Gulf contractors. Massive global shortage of trained engineers — and Indian talent is in highest demand.',
      stats: [
        { value: '₹1.5L+', label: 'Gulf Salary (Tax-Free)', icon: 'money'},
        { value: '50,000+', label: 'Open BIM Jobs Globally', icon: 'building'},
        { value: '10x', label: 'India vs Gulf Salary Jump', icon: 'trending'},
        { value: 'Mandatory', label: 'On ₹100Cr+ Projects', icon: 'trophy'},
      ],
    },
    learningsSection: {
      badge: 'What You Take Home',
      heading1: 'In 2 Hours, You Will',
      headingHighlight: 'See Live',
      heading2: '...',
      sub: 'No slides. No theory. Just one complete building modelled end-to-end — exactly like a Gulf BIM engineer does on day one of the job.',
      learnings: [
        { title: '2D Plan → 3D Building in Revit', desc: 'Watch a flat floor plan transform into a complete 3D building, modelled live from scratch.' },
        { title: 'Clash Detection in Navisworks', desc: 'Find errors in 5 seconds that save contractors ₹5-15 crore on site. The skill Gulf clients pay top money for.' },
        { title: 'BOQ Extracted in 10 Minutes', desc: 'See 3 weeks of Quantity Surveyor work done in 10 minutes — automated from the BIM model.' },
        { title: 'Walkthrough Render Live', desc: 'Generate a cinematic 3D walkthrough — the kind architects pay ₹1 lakh for. Built in front of you.' },
        { title: 'Gulf Workflow Reality', desc: 'ACC Build, ISO 19650, LOD 300 — the exact tools and standards every Gulf project runs on.' },
        { title: 'Career Roadmap to Gulf', desc: 'Step-by-step plan from your first Revit file to a ₹1.5L+ tax-free Gulf BIM role — with realistic timelines.' },
      ],
    },
    toolsSection: {
      badge: 'Real Tool Demos',
      heading1: 'See',
      headingHighlight: 'Real BIM Tools in Action',
      heading2: '— Live, Not Slides!',
      sub: 'Forget theory. Watch the exact tools used on Abu Dhabi airport, Dubai metro and L&T mega-projects — demonstrated live by an engineer who has worked on them.',
      tools: [
        { name: 'Revit', color: '#0696D7', desc: 'The #1 BIM authoring tool — used on 90% of global construction projects.', points: ['2D plan to 3D building live', 'Walls, doors, MEP modelling', 'LOD 300 quality output'] },
        { name: 'Navisworks', color: '#E51F1F', desc: 'The clash detection tool that saves contractors ₹5-15 crore per project.', points: ['Live clash detection demo', 'Coordination workflow', 'Error reports in seconds'] },
        { name: 'ACC Build', color: '#1858B5', desc: 'Autodesk Construction Cloud — the CDE every Gulf project runs on.', points: ['Cloud collaboration live', 'ISO 19650 standard', 'Gulf project workflow'] },
      ],
    },
    agenda: [
      { time: '0:00 – 0:15', topic: 'What is BIM & Why Gulf Pays ₹1.5L+', desc: 'Industry overview, why BIM is mandatory and how Indian engineers can capture Gulf demand.' },
      { time: '0:15 – 0:50', topic: 'Live Demo — 2D Plan to 3D Building (Revit)', desc: 'Watch a real building modelled live in Revit — from blank screen to LOD 300 model.' },
      { time: '0:50 – 1:20', topic: 'Clash Detection + BOQ Extraction', desc: 'Navisworks clash detection live + BOQ pulled from the model in 10 minutes.' },
      { time: '1:20 – 1:40', topic: 'Gulf Career Roadmap & Salaries', desc: 'How to go from ₹18k India site role to ₹1.5L+ Gulf BIM role — exact step-by-step path.' },
      { time: '1:40 – 2:00', topic: 'Live Q&A with Vijayababu', desc: 'Ask anything — Gulf hiring, CV review, career queries, Revit doubts. 11 years of Gulf wisdom.' },
    ],
    whoShouldAttend: [
      'Civil Engineering graduates / final-year students',
      'Mechanical Engineering graduates (HVAC, MEP focus)',
      'ECE / Electrical Engineering graduates',
      'Site engineers stuck at ₹15-25k wanting Gulf shift',
      'Architecture / Interior Design graduates',
      'Diploma engineers with 1-2 years experience',
    ],
    testimonials: [
      { name: 'Karthik Reddy', role: 'B.Tech Civil → BIM Coordinator @ L&T', initial: 'KR', quote: 'I was a site engineer earning ₹18k/month with no future. Vijayababu sir\'s workshop changed my mindset completely. Joined the course, now I\'m a BIM Coordinator at L&T with ₹6.5 LPA. Gulf is my next stop.' },
      { name: 'Rahul Sharma', role: 'Mechanical Eng → BIM Engineer @ Saudi Arabia', initial: 'RS', quote: 'After this 2-hour workshop I knew BIM was my way out. 6 months into the course, I had a Saudi offer in hand. Now earning ₹1.4L tax-free in Riyadh. Vijayababu sir\'s Gulf network is real.' },
      { name: 'Sneha Patel', role: 'B.Tech Civil → BIM Modeller @ Shapoorji', initial: 'SP', quote: 'Best decision was attending Vijayababu sir\'s free workshop. Real demos, real Gulf workflow. Now I work at Shapoorji on Mumbai metro projects. Targeting Dubai next year.' },
      { name: 'Mohammed Farhan', role: 'Civil Diploma → BIM Engineer @ UAE', initial: 'MF', quote: 'I had a diploma — was told Gulf is impossible without B.Tech. Vijayababu sir said skill matters more than degree. He was right. 8 months later I was in Abu Dhabi earning ₹1.6L/month.' },
    ],
    companies: ['L&T Construction', 'Shapoorji Pallonji', 'Tata Projects', 'AECOM', 'Atkins', 'Parsons', 'Dar Al-Handasah', 'Hill International', 'KEO Consultants', 'WSP', 'Ramboll', 'Gleeds'],
    bonuses: [
      { title: 'Top 15 Gulf Hiring Companies List', desc: 'PDF with all major Saudi & UAE BIM contractors — names, recruiters, hiring patterns', value: '₹1,499' },
      { title: 'Gulf-Ready CV Template', desc: 'CV format that gets shortlisted by Saudi/UAE recruiters — battle-tested', value: '₹999' },
      { title: 'Revit Starter Files + Model', desc: 'Complete Revit project file you can open and explore right after the workshop', value: '₹799' },
      { title: 'Free 1-on-1 Career Counselling', desc: '30-minute personal session with Vijayababu on Gulf career strategy', value: '₹2,500' },
      { title: 'Exclusive Course Discount', desc: 'Up to ₹10,000 off if you enroll within 7 days of workshop', value: '₹10,000' },
      { title: 'Gulf Interview Question Bank', desc: '50+ real BIM interview questions asked by Gulf contractors with model answers', value: '₹699' },
    ],
    bonusTotal: '₹16,496',
    faqs: [
      { q: 'Is this workshop really 100% free? Any hidden charges?', a: 'Yes, completely free. No credit card needed, no hidden fees. We want you to see what real Gulf BIM work looks like before deciding to invest in a course.' },
      { q: 'I am from Civil/Mechanical/ECE — is BIM right for me?', a: 'Absolutely. BIM hires across Civil, Mechanical (MEP/HVAC) and ECE (electrical systems) backgrounds. Architecture grads also welcome.' },
      { q: 'Do I need to know Revit or AutoCAD already?', a: 'No prior experience needed. The workshop teaches you what BIM is and shows live demos. The full course teaches Revit, Navisworks and ACC from absolute scratch.' },
      { q: 'Is Gulf placement realistic for someone like me?', a: 'Yes. Vijayababu has placed students in Saudi, UAE and Qatar. Gulf hires by skill, not by degree. With BIM expertise + 1 year experience, Gulf doors open.' },
      { q: 'Will I get a recording if I miss the live session?', a: 'Yes! All registered attendees get the recording within 24 hours. Watch whenever convenient.' },
      { q: 'Will the trainer answer my career questions personally?', a: 'Absolutely. The last 20 minutes are dedicated Q&A. Gulf hiring, CV review, interview tips — ask anything. 11 years of Gulf experience at your service.' },
      { q: 'Is this online or offline?', a: 'It is a hybrid live session — attend either online (Zoom) or offline at our Ameerpet Hyderabad campus. Choose while registering.' },
      { q: 'Will I get a certificate?', a: 'Yes, every attendee receives a Certificate of Participation from Nettms Education — perfect for LinkedIn profile and CV.' },
    ],
  },
}

export function getMasterclass(slug) {
  return masterclasses[slug]
}
